### ISSUE TITLE
Add X-Tags to Standalone Resolution calls

### ISSUE THREAD

**Issue by sjarvie** [URXtech/urx-sdk-web#13]
@jlturner We need to add the publisher tags to the standalone resolution endpoint, atleast for the Pocketmath Units

**Comment by jlturner** [comment]
@sjarvie Need any help here?

**Comment by sjarvie** [comment]
@jlturner I realized that in the SDK we do not have include the third_party tags to begin with, so the official SDK may be fine as is.

If we continue to produce new units, we may want a cookie-cutter type of template to automatically set this field.

**Comment by sjarvie** [comment]
Closing this issue.
